"""End-to-end test: Schrödinger square-well solver generated by a real Ollama LLM.

This test feeds the ``examples/square_well_schrodinger.md`` instruction file
into the full Scientific Loop graph and lets a local Ollama instance generate
the code.  It requires:

- A running Ollama server on ``localhost:11434``
- The ``qwen2.5-coder:32b`` model pulled locally

The test is marked with ``@pytest.mark.ollama`` and will be **auto-skipped**
when Ollama is not available (see ``conftest.py``).
"""

from __future__ import annotations

from pathlib import Path

import pytest

from orchestrator.nodes import configure_llm
from orchestrator.state import ScientificState
from src.cli import build_graph

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_EXAMPLES_DIR = Path(__file__).resolve().parent.parent / "examples"
_INSTRUCTION_FILE = _EXAMPLES_DIR / "square_well_schrodinger.md"
_MAX_ITERATIONS = 5


# ---------------------------------------------------------------------------
# Test
# ---------------------------------------------------------------------------


@pytest.mark.ollama
@pytest.mark.timeout(1800)  # 30 min generous timeout for large model
class TestSchrodingerE2E:
    """Generate a square-well Schrödinger solver from a Markdown spec using Ollama."""

    def test_orchestrator_generates_passing_code(self) -> None:
        """The full Plan→Code→Verify(→Reflect) loop should produce passing tests."""
        # ---- Arrange --------------------------------------------------------
        task_description = _INSTRUCTION_FILE.read_text()

        configure_llm(provider="ollama", model="qwen2.5-coder:32b")

        graph = build_graph(max_iterations=_MAX_ITERATIONS)
        app = graph.compile()  # in-memory, no checkpointer

        initial_state: ScientificState = {
            "task_description": task_description,
            "mathematical_constants": {
                "hbar": 1,
                "m": 1,
                "V0": 50,
                "a": 1,
            },
            "plan": "",
            "code_drafts": {},
            "test_logs": [],
            "reflection": "",
            "iteration_count": 0,
            "ground_truth": [],
        }

        # ---- Act ------------------------------------------------------------
        final_state = app.invoke(initial_state)

        # ---- Assert ---------------------------------------------------------
        # The graph ran at least one iteration
        assert final_state["iteration_count"] >= 1, (
            "Expected at least 1 iteration"
        )

        # All generated tests passed (empty test_logs means success)
        assert final_state["test_logs"] == [], (
            f"Generated tests failed after {final_state['iteration_count']} "
            f"iteration(s):\n" + "\n---\n".join(final_state["test_logs"])
        )

        # The coder produced actual files
        drafts = final_state["code_drafts"]
        assert len(drafts) >= 2, (
            f"Expected at least 2 code files, got {list(drafts.keys())}"
        )

        # At least one file looks like a solver and one like a test
        all_paths = " ".join(drafts.keys()).lower()
        assert "solver" in all_paths or "schrodinger" in all_paths or "square_well" in all_paths, (
            f"Expected a solver source file, got: {list(drafts.keys())}"
        )
        assert "test" in all_paths, (
            f"Expected a test file, got: {list(drafts.keys())}"
        )
